### ISSUE TITLE
Some of the test data should be generated during build time

### ISSUE THREAD

**Issue by kuscsik** [OP-TEE/optee_test#139]
Some of the OPTEE tests will fail if test suite has no write permissions to the TA folder. For example:

XTEST_TEE_1008.4 Load fake uuid TA

can fail with TEEC_ERROR_ITEM_NOT_FOUND if it can't copy the fake TA:

device/linaro/bootloader/optee_test/host/xtest/xtest_1000.c:621: res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0xffff000f = TEEC_ERROR_SECURITY

Read-write access to TA folder should not be not a requirement to run a test. Much better approach would be if the runtime test vector generation would be just limited to the data and temporary folders.

**Comment by jforissier** [comment]
Wasn't this supposed to be addressed by https://github.com/OP-TEE/optee_test/commit/b2865abeac9e9806a9ce785c4504ec1b7221fe50? @d3zd3z what do you think?

**Comment by jbech-linaro** [comment]
So Zoltan's fix here https://github.com/OP-TEE/optee_test/pull/140 kind of revert it, but the difference is that Zoltan fixes the issue by writing SELinux rules instead of avoiding the issue by running it in another folder. Is that correct @kuscsik ? Having that said, as Jerome said, it'd be good to hear from @d3zd3z also.

**Comment by jforissier** [comment]
@jbech-linaro https://github.com/OP-TEE/optee_test/pull/140 does not revert https://github.com/OP-TEE/optee_test/commit/b2865abeac9e9806a9ce785c4504ec1b7221fe50 it just changes the default path so that no new SELinux rule is needed (as far as I can tell).

@kuscsik:
> Much better approach would be if the runtime test vector generation would be just limited to the data and temporary folders.

Are you expecting some other fix in addition to your proposal https://github.com/OP-TEE/optee_test/pull/140? Or is it enough?

**Comment by kuscsik** [comment]
Hi @jbech-linaro, @jforissier 

 I assumed that the copy is done in the main TA folder, since the /data/tee folder is now writable (#140).  But it seems, was wrong about this.
I'm also suspecting an SELinux issue, but I get no error message about a blocked file operation by SELinux (the TA file is just not created). I will do some more debugging.

There are 2 tests failing on Android because of initial file operations. Everything else is now fixed by the new SELinux rules:

https://android-review.googlesource.com/#/c/295569/

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
