### ISSUE TITLE
Some types needed by optee_test are no longer exported by optee_os

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_test#152]
Build failure:

```
/projects/xxx/optee_test/host/xtest/xtest_20000.c: In function 'obj_corrupt':
/projects/xxx/optee_test/host/xtest/xtest_20000.c:292:19: error: invalid application of 'sizeof' to incomplete type 'struct tee_fs_file_meta'
            sizeof(struct tee_fs_file_meta);
                   ^
/projects/xxx/optee_test/host/xtest/xtest_20000.c:294:18: error: invalid application of 'sizeof' to incomplete type 'struct tee_fs_file_info'
           sizeof(struct tee_fs_file_info);
                  ^
/projects/xxx/optee_test/host/xtest/xtest_20000.c:296:7: error: 'BLOCK_FILE_SIZE' undeclared (first use in this function)
       BLOCK_FILE_SIZE;
       ^
/projects/xxx/optee_test/host/xtest/xtest_20000.c:296:7: note: each undeclared identifier is reported only once for each function it appears in

```

Workaround (cut and paste from optee_os... should be done by exposing it in optee_os... or something better changed in optee_test):

```
diff --git a/host/xtest/xtest_20000.c b/host/xtest/xtest_20000.c
index 7580755..130587e 100644
--- a/host/xtest/xtest_20000.c
+++ b/host/xtest/xtest_20000.c
@@ -273,6 +273,26 @@ static int is_obj_present(TEEC_UUID *p_uuid, void *file_id,
         return 0;
 }
 
+/* bodge up unexported type */
+#define NUM_BLOCKS_PER_FILE	1024
+
+struct tee_fs_file_info {
+	size_t length;
+	uint32_t backup_version_table[NUM_BLOCKS_PER_FILE / 32];
+};
+
+struct tee_fs_file_meta {
+	struct tee_fs_file_info info;
+	uint8_t encrypted_fek[TEE_FS_KM_FEK_SIZE];
+	uint8_t backup_version;
+};
+
+#define BLOCK_FILE_SHIFT	12
+
+#define BLOCK_FILE_SIZE		(1 << BLOCK_FILE_SHIFT)
+
+
+
 static TEEC_Result obj_corrupt(TEEC_UUID *p_uuid, void *file_id,
 		       uint32_t file_id_length,
 		       uint32_t offset, enum tee_fs_file_type file_type,
```

**Comment by lackan** [comment]
Hi, I remember that last time I built optee_test, and I don't have such errors. Do you have something different with us?

**Comment by lws-team** [comment]
It's likely I have something different, because there's no top level project with optee that includes the dependencies as submodules so the global build is readily reproducible.  And there are a lot of repos and conflicting / outdated info.

These were taken from the HEAD of the github repos

submodule|HEAD
---|---
optee_os|605373e core: fix mem leak in tee_fs_rpc_new_closedir()
optee_test|6203b87 Format UUID strings correctly
optee_client|1d5cc96 Allow O to be an absolute path

On kernel side - for hikey - I forward-ported patches from here

https://github.com/linaro-swg/linux/tree/optee

These create /dev/tee0 and teepriv0 ... tee-supplicant wants `/dev/opteearmtz00` is there something else needed?

**Comment by vchong** [comment]
Hi Andy,

Good to hear from you and hope you're doing well! :)

Have you looked at https://github.com/OP-TEE/manifest and https://github.com/OP-TEE/build? If you follow the instructions on https://github.com/OP-TEE/optee_os#5-repo-manifests (which utilizes both repos above), they will build a full stack for you that you can run on QEMU/HiKey/etc. Kernel is also taken care of so you don't have to do any porting yourself unless you choose to. The default pulls everything from HEAD on master so while there's a possibility of bugs, they don't happen often or get fixed relatively quickly. Alternatively, you can use the 'stable' version of the manifests, e.g. `hikey_stable.xml`, i.e. no build errors, but just that they're not the latest and greatest. Or, you can maybe try the 2.2.0 tag for all 3 repos you listed above to make sure they're compatible.

HTH

**Comment by vchong** [comment]
Oh, also, if you prefer using git submodules, you can also look at https://github.com/linaro-swg/hikey_optee, but this is HiKey only and looks like it hasn't been updated for a while.

**Comment by lws-team** [comment]
@vchong Thanks...

The manifest just does what I already did for the relevant parts of hikey.xml.  I don't want to follow the whole 'world' in the manifest.

```
<remote name="optee" fetch="https://github.com/OP-TEE" />
...
<project path="optee_os" name="optee_os" />
	<project path="optee_client" name="optee_client" />
<project path="optee_test" name="optee_test" />
```

However my optee_os is old, from Oct, not HEAD.  I forced it to HEAD and this patch is not needed.... so just my own local confusion.

My project has its own submodules, but I think maybe OPTEE itself should bind its own components using submodules that have internal deps like _test does on _os.

I will close this... but can you let me know the story of /dev/opteearmtz00 vs /dev/tee0?  Or at least where to read about it.

Also is there a pkcs #11 bridge implementation somewhere?

**Comment by vchong** [comment]
You're welcome!

Not sure what story you're looking for exactly, but generally, there was an old and a new (generic) version of the driver. The old one was built as a module by default but it was [deprecated](https://github.com/OP-TEE/optee_linuxdriver/blob/master/README.md) as in release 2.0.0 in favor on the new one which is builtin and currently sent for review in mainline - [v12](https://lkml.org/lkml/2016/10/28/244) as of Oct. You can also read a history/discussion of its initial development [here](https://lists.linaro.org/pipermail/tee-dev/2015-March/000019.html).

As for pkcs#11, sorry but not sure about this either. libtomcrypt is used as the software based crypto module and it seems like only pkcs#1 (1.5) and 5 are supported.

**Comment by lws-team** [comment]
Basically "why does current optee-client want /dev/opteearmtz00 when the kernel gives it /dev/tee0".

It looks like my patches, uplevelled from 4.5 here

https://github.com/linaro-swg/linux/tree/optee

should be updated off the mailing list link, thanks for that.

pkcs#11 would be more a wrapper on the normal world side.  So,eg, openssl can use those apis to get crypto jobs done on the secure side.

**Comment by vchong** [comment]
There's no wrapper to it directly. Imo, the GP client side (normal world) API currently is somewhat limited, and you'd have to call TEEC_InvokeCommand (sort of like an ioctl call) and pass a command to a TA (which you'll have to write) on the secure side to do what you want, but looking at the GP Internal Core API spec, only pkcs#1/1.5 and 5 are supported as well, so you might also have to implement the full protocol yourself in the TA using primitive crypto ops. Sorry, not much help :(.

**Comment by jbech-linaro** [comment]
Hey Andy,

I'm also on holiday, but I've been following both this and the other issue you've had in https://github.com/OP-TEE/optee_client/issues/73 and I'm a bit confused how you're setting up your environment. Victor pretty much already described it, but for clarity I'm chiming in also.

**Build / boot / test issues**
> @lws-team 
> And there are a lot of repos and conflicting / outdated info.

What is conflicting and what is outdated?

For QEMU, HiKey, Juno, MTK8173 and RPi3 we doing releases based on repo setup's according to section 5.x i.e. our [Repo manifest's](https://github.com/OP-TEE/optee_os#5-repo-manifests) and besides that it's the pre-reqs in [4.1](https://github.com/OP-TEE/optee_os#41-prerequisites) that is important. There you will find two variants, stable releases and the ones that track master branches upstream (tip/HEAD). We're doing stable releases every quarter and those are well tested. If there is something that hasn't been tested or has a know bug, then it's mentioned in the [CHANGELOG.md](https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md#tested-on) file. Last release was in October this year and HiKey was tested OK there.

If you instead use the non-stable (which basically everyone in the team uses), then you indeed have a "non-stable" branch. Having that said, been working with this for a couple of years now I can tell that it's not very often that one fails. It is actually pretty stable. Most often when people report issues it's that they have forgot to update all git's and therefore the user could end up with some version skew. For example, let's say that we update secure storage functionality in optee_os, then we also update optee_test by adding new test cases etc. Updating only one of them will most likely cause failure, either build dependency (not that likely) or that xtest fails to run all tests OK. This is the price we have to pay when working with tip/HEAD. But again, if you `repo sync -d` then I'm almost 100% sure you will get back into a working state.

Also, we both build and test (using QEMU) all OP-TEE OS pull request and most often [Travis](https://travis-ci.org/OP-TEE) shows a green light, which indicates that it build OK for all platforms (including the non-repo based) and that xtest passed on QEMU.

I've just a couple of weeks ago updated the file that should serve as the FAQ on optee.org, where I've covered quite a lot of common issues we've seen. I hope @ShovanSargunam will move the information from there to the real FAQ on optee.org soon. But until that happens, feel free to have a sneak peak here: https://github.com/Linaro/website/blob/master/Linaro.org/initiatives/OP-TEE/faq.md

I'm not saying that we never have issues, because we do of course, but quite often after some investigation we figure out that it's the user that has done something wrong, missed some steps etc. But based on our own daily use, i.e., with tip/HEAD and stable releases and automatic builds and tests and a bit surprised when I hear that our repos are conflicting and out of date and therefore highly interested in knowing what we've missed.

**optee_client /dev/xyz**
> @lws-team 
> These create /dev/tee0 and teepriv0 ... tee-supplicant wants /dev/opteearmtz00 is there something else needed?

What? tee-supplicant as Victor hasn't asked for otpeearmtz00 since we used the old deprecated optee_linuxdriver. The driver we've been using for more than a year uses /dev/teeprivX, see devname here:
https://github.com/OP-TEE/optee_client/blob/ce5fefe6cba5df9b4f31399b1155ba768eee0b78/tee-supplicant/src/tee_supplicant.c#L344-L346

And libteec uses /dev/teeX, see here.
https://github.com/OP-TEE/optee_client/blob/master/libteec/src/tee_client_api.c#L125-L127

The only thing related to that is the "ta_dir" name, which is by default: "optee_armtz" (i.e. `/lib/optee_armtz`). But with that wrong, then **no** test in xtests works and if that happens, then you've probably done something not according to the instructions.

This really indicates that you're doing something else than described in our repo instructions for HiKey.

**Linux kernel branches**:
This is our biggest headache, partly because we haven't been able to upstream the driver yet and partly because some devices uses their own forks. Our "rule" is pretty simple. If we can, we use the "optee" branch at https://github.com/linaro-swg/linux which currently points to a  v4.5 branch (vanilla kernel + TEE driver patches). If we cannot use that, then we create a fork. For example RPi3 doesn't have many AArch64 patches in upstream kernel. So we've taken they "best known" AArch64 branch for RPi3 and put our TEE driver patches on top. But for the end user he or she should not need to worry too much about that, since again, the repo manifest will take care of that.

Regarding v4.9, it's still "not supported" (even though we know it's working fine, since we've been using it internally). The plan is to step up officially to v4.9 in the OP-TEE 2.3.0 release, which will be released at the end of January 2017.

**PKCS#11 support**
We have no pkcs#11 support in OP-TEE and there are no plans to add it. We're following the crypto API as defined by GlobalPlatform since it's a GlobalPlatform based TEE. I haven't heard that GP plans to add directly cryptoki support. If one strictly would like to use cryptoki, then one could probably implement a pkcs#11 Trusted Application that acts as a layer between NW userspace -> SW user space and the GP Crypto API in the TEE itself.

Long answer, but I hope I clarified a few things.

// Joakim

**Comment by lws-team** [comment]
@jbech-linaro  Thanks.

First... in Taiwan where I live everyone is at work / school over the West's jolly pagan ritual... except NYD... the big bash is CNY a few weeks later.  I'm also in Japan for a customer, although today I hope to do some gawking.

1) From your personal pov everything is no doubt clear since you focus on this.  From my pov coming to it cold, it's all over the place.  Everything in github means everything is equally definitive and equally visible in google... so there is swg github for this, there are two conflicting archaeological strata on 96boards advice, there are OPTEE repos and there are several flavours of atf including an official arm rep one (that iirc doesn't do hikey).  Please, have a google like a newb would and see what comes up.  Is it today's preferred path for putting it all together coming up?

Most of the swg repos are months old, in cases like swg atf there are a dozen branches with no sign the repo nor the branches are not definitive.  You may know that repo is deprecated, the work done and gathering dust, google doesn't, github doesn't, "linaro swg version" sounds like a reasonable bet then.  
(One thing that would help a bit is rename the abandoned repos -deprecated or so.  Editing the master README.md alone won't solve it if there are many branches or tags.)

When combined with hikey UEFI build process coordinating the interdependent build flow in one step across **seven** discrete external repos with no pinning, it's really extremely fragile.  It's not a ding on you guys, since the work here is clearly good.

Since there are at least two points with genuine child submodule deps in reality (optee_os [ atf optee_client optee_test ], and linaro-edk2 [ optee_os uefi_tools OpenPlatformPkg ] someone ought to maintain those "containers" with pinned, tested, known-good submodule checkouts.  I saw somebody went down that road in swg and props to them, but a) it's abandoned and b) they put too much in it at the top level.  To enable people to consume optee without hikey, and to consume hikey uefi [+ optee container], it just needs the two parent containers above, uefi containing the optee parent.

2) The actual code looks very solid.  It's the project meta-structure that is fragile... things like atf version dep on optee failing isn't a one-off, it reflects atf eats optee headers without any version pinning.  It's no good countering that with 'it almost always works'... I believe you, but there is something to do structurally here.  You might also think about runtime epoch numbering in the structs, so if people do fall over it, it says "atf uses v15 optee headers but optee using v21".

Why is there a '96boards atf'?  Why not at least upstream it, or better work on it in the arm repo and eliminate these proliferating forks?

3) repo is ok for androiders but git submodule is built into git everybody uses, and doesn't try to force me to use a particular build flow.  Where there are compiletime deps, pinning in git just for those is preferable seems to me.

4) opteearmtz.... seldom is the user actually crazy.  I built everything correctly and scp'd it on a prebuilt rootfs....as luck would have it there are ancient (2015.11) userland pieces (both the apps and libs) already in the rootfs on different paths.  Since people are going to typically get started on such a rootfs, this should be a gotcha (although half the problem is google finding your way to that list of gotchas).

5) kernel was actually reasonable... I found the 4.5 tree and forward-ported those... I think that was working ok immediately, just obfuscated by atf breaking it.  It'd be nice if there was a tree matching last upstreamed patches + basis as well but not the biggest problem.

6) What I need to end up with is openssl using a private key that never leaves optee, along the lines of a 'key vault'  I asked on the openssl list, from their side the answer is to use an 'engine', and they have a pkcs#11 engine.  So it's not pkcs#11 that is the goal but openssl... is there another way where some of the shim stuff exists?

Thanks.

**Comment by lackan** [comment]
Hi Andy,

For the openssl, there is a branch in optee_os implement it(https://github.com/OP-TEE/optee_os/tree/poc/openssl_cryptolib),  I'm not sure whether it can help you.

**Comment by lws-team** [comment]
@lackan thanks... that sounds great, I will take a look... poc == Proof of Concept?

**Comment by lackan** [comment]
@lws-team Yes, I think you are right.

**Comment by lws-team** [comment]
@lackan ... thanks for the tip, it's basically a fork with an import of openssl into optee from a couple of years ago.

Global platform has a spec about secure exchange over http, but it seems to want to do the whole thing in secure world if I understood it.

I guess that's one way, sidestepping the whole openssl engine business... just proxy https-encrypted network traffic in nonsecure for openssl + small web client living wholly in secure world.

**Comment by jbech-linaro** [comment]
Hi Andy,

> @lws-team
> From your personal pov everything is no doubt clear since you focus on this.
> From my pov coming to it cold, it's all over the place. 

I see what you mean now and regarding finding information I agree that I can
be confusing for people in some cases like for HiKey for example, where there
also exist some documentation on other 96Boards pages. This is something we're
aware of and we're trying to collaborate pages in general in Linaro, not only
things related to our parts.

But I don't agree that it's "all over the place" in general. I'd say that HiKey
is an exception, if you're trying to use another device for OP-TEE, most other
information you will find will point to OP-TEE/optee_os and some information are
a bit dated, but not the information how to build and how to run, that is all up
to date according to my knowledge and I'm the one that usually keeps that
up-to-date.

Having that said, from now on, please consider our pages, i.e, the project pages
as the main source for how to work with OP-TEE and then mainly OP-TEE/optee_os
where we've been trying to consolidate our information. We are the ones working
with this on day to day basis and other guides etc are derived from our
information at some point and I can't vouch for them.

> @lws-team
> Most of the swg repos are months old, in cases like swg atf there are a dozen
> branches with no sign the repo nor the branches are not definitive.

Most? Talking about stable or latest? Stable builds are since last release, i.e,
October 2016 all according to our quarterly release schedule. For latest, let's
go through them for HiKey based on the commits I got when checking it out today
from scratch, to see where we are and if "most" are months old.

|git|commit|status:branch|comment|
|---|------|------|-------|
|build| 67959e1 | Latest:master | |
|optee_client| 1d5cc96 | Latest:master | |
|optee_os| ae3ca14 | Latest:master | |
|optee_test| 6203b87 | Latest:master | |
|aes-perf| 8e5a5f9 | Latest:master | |
|sha-perf| 1ef3101 | Latest:master | |
|hello_world| a17da73 | Latest:master | |
|gen_rootfs| 6173dea | Latest:master | |
|patches_hikey| 5f4024c | Latest:master | |
|linux| 0adbb24 | Linux4.5:optee | This contains all latest and greatest for our TEE driver development, the kernel itself is a bit dated but TEE patches are pristine |
|busybox| dbf5a6d | Not latest | At Busybox v1.25 I think there was an issue and we decided to use a tagged version |
|arm-trusted-firmware| 63655eb | Latest:96boards-hikey | That is HiKey's ARM-TF branch, we're just using it |
|burn-boot| db522b1 | Latest:master | 96Boards git, just using it |
|l-loader| cddd213 | Latest:master | 96Boards git, just using it |
|edk2| 7da6cdf | Latest:hikey | 96Boards git for EDK2, just using it |
|grub| 07662af | Latest:master | Just using it |
|strace| f73c5cf | Latest master | Actually found a build issue here this morning |

So, out of 17 git's we are using. ALL pure OP-TEE branches are running latest
(the first 9 in the table) and most of the rest does too.  Linux will be stepped
up to use 4.9 in next release. Busybox uses a pinned version. Grub and strace
just tracks latest upstream. Burn-boot and lloader are HiKey specific and to my
knowledge we are using the correct ones here and just follows upstream. ARM-TF
and EDK2 are not pointing to true upstream repos, i.e, they are pointing to
96Boards gits instead of ARM and TianoCore. As soon as the 96Boards folks has
managed to upstream their patches to the official repos, we will just switch, if
that ever happens I don't know. We're just following a long and uses what the
96Boards team are creating.

So can we know agree that we (the OP-TEE project) have both stable releases
tagged/pinned across gits and that we have other setups running mostly latest?

Since you're talking a lot about ARM-TF I can mention that we have an ongoing
dialogue with ARM regarding the header parsing of the TEE binaries. They (ARM)
are working on implementing this on their side with the goal to include it in
the official ARM-TF tree. When that is done we won't have to use our specific
ARM-TF patches any longer and then we will just switch to point direct to
upstream. Meanwhile we rebase our ARM-TF branch once in a while.

> @lws-team
> Why is there a '96boards atf'? Why not at least upstream it, or better work on
> it in the arm repo and eliminate these proliferating forks

The simple answer is not enough engineers available working on it. To my
knowledge the 96Boards team are doing as good as they can and they are indeed
upstreaming patches to official ARM-TF. Feel free to chime in and help if you
have time. It would help and make everyone happy.

> @lws-team
> repo is ok for androiders but git submodule is built into git everybody uses, and doesn't try to force me to use a particular build flow.

Regarding "git submodules" vs "repo" (or any other SCM) we had that discussion when
we started the project and in the end we decided to go ahead with repo instead
of git submodules, since we believed it was more suitable for us. There were
(and still are) people in the team the would prefer git submodule, but again
the decision has been made and we have no plans to change it. If you don't like
it or don't want to learn it, well, then sorry, not much we can do. Don't forget
that after running "repo init and repo sync" (two commands!), then you can use
git just as usual. So, it's not really a steep learning curve.

If I would have been in your situation I would start out by following the
official instructions and when I know I have a working setup, then I'd start
tweak things according to my way of working. I totally understand that you've
had a hard time to get things working by just cloning manually and building on
your own. Even the stripped down setup we host and maintain is pretty
complicated under the hood, which again is why we created a) build.git (helper
makefiles) b) using repo to track interdependencies and tag/pin commits across
all gits for stable releases.

Since it seems like you're interested in HiKey and want something stable, then
I urge you have a look here:
https://github.com/OP-TEE/manifest/blob/master/hikey_stable.xml

There you have every single repository listed with the branch name and the
exact commit. You can clone all that by hand if you prefer doing so, but, just
to make it clear that it is very easy to use repo. This morning, just to write
this reply as detailed as possible I did a clean setup for HiKey using the
stable OP-TEE 2.2.0 release (at this point in time this was master tip/HEAD,
i.e, we're talking about October 2016).

What I did was (I have pre-reqs installed as stated in optee_os/README.md and I
have downloaded "repo" into my PATH. Repo is just is a simple script, no
installation nothing else)

First, I got all the source code and compiled it:
```bash
# Console #1
$ mkdir hikey
$ repo init -u https://github.com/OP-TEE/manifest.git -m hikey_stable.xml
$ repo sync -j3 
$ cd build/
$ make toolchains
$ make all -j4
```

So, after **6** lines in bash I had all that completed. Next I needed to flash
the device. Here, you can get into trouble if you have a very very old setup.
The question here is basically if you have fastboot or not already running on
your device. But, if you have fastboot already (which has been default on HiKey
for more than a year I think) then ...


```bash
# Console #2
# In a second console attach to the UART (needs the UART extension board, since
# default configuration is configured to use that board). Don't like picocom?
# use minicom or some other tty software ..
$ picocom -b 115200 /dev/ttyUSB0
```

```bash
# Console #1
$ make flash # Follow the instructions there (jumpers) ...
```

The I just cut the power to the device and boot up again.

```bash
# Console #2
# Bypass the: "Android Fastboot mode - version 0.4. Press any key to quit."
# Select: [2] boot from eMMC
# Let GRUB boot the default ...
```

When I have the prompt, I simply run xtest (tee-supplicant is automatically
started on HiKey).

```bash
root@HiKey: xtest
...
23476 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

So, all works just fine on this tagged/pinned release across all our gits in use
and that was again done in October 2016, the next release is in January 2017. We
can't and don't want to release more often than quarterly.

The non-stable on the other hand (which is the base for next release):
https://github.com/OP-TEE/manifest/blob/master/hikey.xml

I had an issue when building strace, seems like they just recently made some
changes so I had a compile issue both on my Ubuntu-based and Arch based machine.
If I figure out the issue, then I'll send a patch to strace project.

> @lws-team
> opteearmtz.... seldom is the user actually crazy. I built everything correctly
> and scp'd it on a prebuilt rootfs....as luck would have it there are ancient
> (2015.11) userland pieces (both the apps and libs) already in the rootfs on
> different paths. Since people are going to typically get started on such a
> rootfs, this should be a gotcha (although half the problem is google finding
> your way to that list of gotchas).

Sorry I don't agree. I'm repeating, you've followed something not created by the
OP-TEE team and then we can't vouch for it.

> @lws-team
> kernel was actually reasonable... 

Hah, the thing that I though should be the trickiest to get right is the thing
that you though was pretty easy, I'm glad to hear that was easy :)

> @lws-team
> What I need to end up with is openssl using a private key that never leaves
> optee

Alright, saving private keys are a bit tricky to deal with. Ideally you'd like
to have a crypto IP with capability to derive new keys. Some devices have that,
some don't. Having that said, you can store data securely using the secure
storage API from A Trusted Application point of view.

Btw, I saw the other messages between you and lackan and the openssl branch he
mentioned has another purpose. It was just used as a proof of concept when we
implemented the cryptographic abstraction layer showing that you can quite easy
switch the default crypto lib (LibTomCrypt) with some other software (or
hardware implementation). So, don't both looking into that for the thing you are
interested in.

I think this is my record in a long answer on GitHub. If you have more questions
or need more clarity about what is pinned and not, what is using latest or not
or how to setup OP-TEE on HiKey, please reach out to me and I'd be happy to
setup a Hangout for an hour or so when I'm back from my holiday.

// Joakim

**Comment by lws-team** [comment]
hehhhhh.... okay.  I think you should probably enjoy the rest of your hols, since everything is already perfect.

It'd've been nice to fix these things for others, but I already wasted the time personally and used up the time of the guys kind enough to help me.  In the tree for my customer these things are bolted together with submodules and documented in markdown in the tree, that's the best I can do about it.
