### ISSUE TITLE
Accurracy issue in xtest performance tests

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_test#170]
AES and hash test are based on measuring time spent for each invocation from Linux userland client of a command against the TA performing a single buffer AES ciphering or hash computation.

The issue I faced when experiencing this on HW for non-huge buffers (< 1MByte) is that TA invocation is quick (far less than 10ms), that the Linux scheduling generates to much timing deviations for an accurate throughput measurements.

For comparing OP-TEE performances for various setup (HW configs and/or OP-TEE releases), we need quite stable numbers. Could one crosscheck the tool (i.e `xtest --aes-perf` with buffer sizes (`-s` argument) from 1kByte to 128kByte) on some HW and give their feedback ?

**Comment by igoropaniuk** [comment]
I also noticed similar results even in QEMU, when I was moving aes-perf/sha-perf standalone benchmarks to xtest. The main concern is: until the time spent in TA commensurate(it's within the same) with the time spent for bypassing through all OP-TEE layers (optee-client->libutee) you will get such inaccurate results.

I think all benchmarking code should be moved to TA side. NW client will InvokeCommand to start benchmarking, and all other stuff is going to be inside TA (allocate buf, perform n repeats of aes/sha operation, send results back to nw client)

**Comment by jforissier** [comment]
It would be quite trivial to add an option to tell xtest to measure the time in the TA only (well... maybe not if we need better than ms resolution...).

In the mean time, you may also try to increase the inner loop count in order to reduce the influence of the time spent in the intermediate layers between NW and SW.

**Comment by etienne-lms** [comment]
The idea is to get the throughput measurement including the nonsecure/userland to secure/userland traversal and way back, as it is part of the figure. 

The best I found is to run several invocations, measure the global time spent and divide it by number of invocations. But i failed to quickly setup something friendly (another xtest argument about a "loop" counter, etc...). And i'm on holidays next week, so i rather ask someone else to do the job while i'll be skiing :)

**Comment by jforissier** [comment]
Let's try to quantify this inaccuracy/instability issue. This is basically the standard deviation value.

I'm getting reasonably stable results on HiKey, judging from the standard deviation values. In order to make it easier to see, I have updated xtest to also display the coefficient of variation (cv) expressed as a percentage, and the 2-sigma confidence interval (if -v is given). Here is how it goes for 1K:
```
root@HiKey:/ xtest --aes-perf -v
Starting test: ECB, encrypt, keysize=128 bits, size=1024 bytes, random=yes, in place=no, inner loops=1, loops=5000, warm-up=2 s
min=56.666μs max=83.334μs mean=57.5378μs stddev=1.72413μs (cv 2.99652%) (16.9725MiB/s)
2-sigma interval: 54.0896..60.9861μs (16.0129..18.0545MiB/s)
```
What this means is: 95% of the 5000 calls took between 54 and 61 microseconds which is 57 (the mean) plus or minus 6% (2 times the coefficient of variation). So even if the scheduling or any other event spreads the results a bit, it's not all over the place (although I agree 12% amplitude is not a small interval). 95% is a property of the 2-sigma interval. Expressed as throughput, we got between 16 and 18 MiB/s for 95% of the calls.
So, simply by looking at the coefficient of variation you have an indication of the spread.

For 128K it's a bit better (cv 1.7% down from 3% for 1K):
```
root@HiKey:/ xtest --aes-perf -v -s 131072
Starting test: ECB, encrypt, keysize=128 bits, size=131072 bytes, random=yes, in place=no, inner loops=1, loops=5000, warm-up=2 s
min=174.166μs max=222.5μs mean=176.308μs stddev=3.09334μs (cv 1.75451%) (708.987MiB/s)
2-sigma interval: 170.121..182.495μs (684.951..734.77MiB/s)
```

In order to compare values between platforms or builds, one has to check this 2-sigma interval. My understanding is, if intervals overlap, the comparison is not statistically significant.

Here are the relative coefficients of variation for buffer sizes between 1K and 130K.
```
root@HiKey:/ for i in 1 `seq 10 10 130`; do s=$(($i\*1024)); echo -n "${i}K: "; xtest --aes-perf -v -s $s | grep stddev | sed 's/.*cv \([0-9.]\+%\).*/\1/'; done
1K: 3.22566%
10K: 2.83231%
20K: 2.81746%
30K: 2.7152%
40K: 2.54283%
50K: 2.58002%
60K: 2.33347%
70K: 2.16098%
80K: 2.1092%
90K: 1.93583%
100K: 1.95558%
110K: 1.83431%
120K: 1.8649%
130K: 1.83938%
```

So, since you mentioned comparing releases: let's assume we're checking the performance of a new release and want to detect any regression. Let's also assume that the cv numbers are about the same for both releases. Then the numbers show that unless a regression impacts the speed by more than 7-13% (2 x 2 x cv) we would not be able to detect it reliably.
Are the numbers good or bad? Well, at least we do have numbers and we know what they mean, so we should be able to come to reasonable conclusions ;)

I'll try QEMU to see if I get similar results.
