### ISSUE TITLE
xtest failed 

### ISSUE THREAD

**Issue by j824737450** [OP-TEE/optee_test#263]
Hi,
I run op-tee on imx6q sabrelite. Run the xtest , and the result is that 
![image](https://user-images.githubusercontent.com/33032927/37088975-07a08f6e-223a-11e8-97fb-32ba2fbb3437.png)
![image](https://user-images.githubusercontent.com/33032927/37089097-6bc634c6-223a-11e8-8512-398017bb5046.png)
![image](https://user-images.githubusercontent.com/33032927/37089104-72e83eb6-223a-11e8-847d-99fd4c4b3d0c.png)

What's wrong with the failures? What are the causes of failures?Do these failures have any impact on the system?

Thank you!

**Comment by jforissier** [comment]
Hi @j824737450,

I think your `optee_os` is outdated wrt. `optee_test`.

- The failures in 6007 are most likely caused by https://github.com/OP-TEE/optee_test/commit/3e7d1075115924cf96c21392ed07a85fdec355a8, which is a regression test for the following commits: https://github.com/OP-TEE/optee_os/compare/e1c9896720e9%5E...94a72998bc1d
- As for 1006, I wouldn't be surprised if it was caused to https://github.com/OP-TEE/optee_test/commit/04511d8bcf10 which tests https://github.com/OP-TEE/optee_os/commit/b0961f98d94d.

Your options are either to update your `optee_os`, or use an older version of `xtest`.

**Comment by j824737450** [comment]
Yes, you are right!  I  update my optee_os.
![image](https://user-images.githubusercontent.com/33032927/37131097-d01912b8-22c1-11e8-81c2-028bafc9bb5f.png)
Thank you!
