### ISSUE TITLE
Xtest Illegal Instruction

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_test#300]
Hello,

I'm booting Linux + OP-TEE on Nitrogen6x. However, when trying  to run xtest I get an Illegal Instruction error. Also, I disabled CAAM on the kernel.

Thank you.

**Comment by glneo** [comment]
+1
I am now seeing the same on AM43xx which also has a Cortext-A9 CPU. I will attempt to track this down and report back.

**Comment by glneo** [comment]
Okay, root caused it, looks like the problem is in the pre-compiled libcrypto.a library for ARMv7 added here:

https://github.com/OP-TEE/optee_test/commit/27054ff9aaf42168ae178a46a5b89c059bb1113d

It was compiled targeting Cortex-A15:

From readelf:
```
[...]
File Attributes
  Tag_CPU_name: "Cortex-A15"
[...]
  Tag_DIV_use: Allowed in v7-A with integer division extension
```

This leads to the compiler generating udiv instructions, which are not available to us lowly Cortex-A9 users :(

```
(gdb) r
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00054c30 in lh_insert ()
(gdb) x/i 0x00054c30
   0x54c30 <lh_insert+22>:	udiv	r3, r3, r2
```

@jforissier ,

Could you rebuild this library and target a lower common denominator core, like A7/8? That should work on all currently supported ARMv7 platforms.

Thanks,
Andrew

**Comment by jforissier** [comment]
@glneo sure, I will look into it tomorrow.

**Comment by jforissier** [comment]
Hi @glneo,

Would you please try `libcrypto.a` compiled as follows? Thanks.

```
git clone https://github.com/openssl/openssl.git
cd openssl
git checkout OpenSSL_1_0_2o
./Configure linux-generic32 -mcpu=cortex-a9 no-shared --cross-compile-prefix=arm-linux-gnueabihf-
make build_libcrypto
# Should generate ./libcrypto.a
```

**Comment by glneo** [comment]
Yes, this generated a working libcrypto.a.

**Comment by jforissier** [comment]
OK, good. So let's use it instead: https://github.com/OP-TEE/optee_test/pull/302

**Comment by PedroRibeiro95** [comment]
I think the problem has been tracked and resolved. I will close the issue now, thank you
