### ISSUE TITLE
A question about regression_5000

### ISSUE THREAD

**Issue by sticfeynman** [OP-TEE/optee_test#324]
In the AllocateSameMemory_twice() and RegisterSameMemory_twice(), it seems to expect this is reasonable or legal to register or allocate the same shm in a raw. Is this a normal behavior in the user application?  At least, I feel it would have a resource leak if there is no TEEC_ReleaseSharedMemory() in the middle of these two consecutive AllocateSharedMemory() or RegisterSharedMemory().

**Comment by etienne-lms** [comment]
I think it is the CA responsibility to free resources allocated from `TEEC_AllocateSharedMemory()`/`TEEC_RegisterSharedMemory()`. The lib/optee make no assumption on CA behavior. Not releasing shm may indeed leak space in shm until CA dies. "May", not "will" since dynamic (-ally mapped) shm does not suffer much from shm leakage, below.

> Note that this does not create a memory leak as memory must be already allocated before calling registration.

@c-auger not that this is not true if `CFG_CORE_DYN_SHM=y`. See doc on [Noncontiguous shared buffers](https://optee.readthedocs.io/en/latest/architecture/core.html?highlight=CFG_CORE_DYN_SHM#noncontiguous-shared-buffers).
The doc could be updated to mention `TEEC_RegisterSharedMemory()` in that section.
