### ISSUE TITLE
Several xtests failing - Common error - TEEC_ERROR_ITEM_NOT_FOUND

### ISSUE THREAD

**Issue by ashwinnirantar** [OP-TEE/optee_test#351]
I am running xtest on my platform. Getting this error **TEEC_ERROR_ITEM_NOT_FOUND** for a few tests, precisely these were the numbers - 

```
15708 subtests of which 115 failed
74 test cases of which 14 failed
0 test case was skipped
TEE test application done!
```

The full error was similar to this - 

**regression_1006 Test Basic OS features**
```
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+5659bceaa0-r0/git/host/xtest/regression_1000.c:551: xtest_teec_open_session(&session, &os_test_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1006 FAILED 
```

**regression_8001 Test TEE Internal API key derivation extensions**
```
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+5659bceaa0-r0/git/host/xtest/regression_8000.c:725: xtest_teec_open_session(&session, &crypt_user_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_8001 FAILED
```

**Comment by jbech-linaro** [comment]
What platform? How did you build it? Like this (https://optee.readthedocs.io/building/gits/build.html#build) I suppose? How have you debugged the issue and what is your own conclusion?

**Comment by ashwinnirantar** [comment]
> What platform? How did you build it? Like this (https://optee.readthedocs.io/building/gits/build.html#build) I suppose? How have you debugged the issue and what is your own conclusion?

Unfortunately, I cannot disclose the platform, but these are some of the details -->

**Linux Kernel version** 4.19.34
**Yocto Thud release** 
**meta-linaro layer**

git describe gave the following output -->

`$git describe --all --abbrev=8 HEAD^`
`tags/16.01-263-g0a94dece`

`$git describe`
`14.05-580-gb30036d`

I built the yocto image by including the meta-linaro layer and then including the optee tools in the image (optee-test, optee-client, optee-examples)

**Comment by ashwinnirantar** [comment]
@jbech-linaro Can you help please? The thing is, I am getting the TEEC_ERROR_ITEM_NOT_FOUND only for the 1xxx family of tests - which make use of the os_test trusted application. The following tests are failing, all with the same error - xtest_teec_open_session(&session, &os_test_ta_uuid, ((void *)0), *ret_orig) has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS

What is usually the cause of this error? 

I tried to debug a lot but was not able to understand it. I removed the Trusted application (e.g. storage TA) from the default location /lib/optee_armtz, I got the same error for the 6xxx family of tests, but in addition to this, it also mentioned the "TA not found" error. I also tried the same for the os_test TA by removing it from /lib/optee_armtz, but again got "TA not found". The test cases are failing even when the TA is in the correct location. 

What may be the cause of this error in normal cases that you have observed? According to the client specifications API by GlobalPlatform, the open session has a few parameters, can failure to locate one of those parameters generate this error? 

Thank you.

**Comment by ashwinnirantar** [comment]
Moreover, I know what the "TEEC_ERROR_ITEM_NOT_FOUND" error means, but it would be great if I could get an example when this error is generated. One example would be when the TA is not found by the tee-supplicant, but in that case - TA not found error is also generated. So what can be some of the cases when this error is generated? How can I know more about what might be causing the error? 

Any help would be appreciated.

**Comment by jbech-linaro** [comment]
Firstly, those Yocto builds seems to not be maintained any longer (see [this](https://github.com/OP-TEE/optee_os/issues/3055#issuecomment-497668581)) and those have always in the past been maintained by people not working directly with OP-TEE. Secondly it would help if you could provide a full log from both non secure as well as secure side when running the 1006 test, please also enable debug prints (`CFG_TEE_CORE_LOG_LEVEL=3 and CFG_TEE_TA_LOG_LEVEL=3`).

> Moreover, I know what the "TEEC_ERROR_ITEM_NOT_FOUND" error means, but it would be great if I could get an example when this error is generated.

That error code isn't found in many places and most of them are actually checks not sets. So a few debug prints around those might be a good start.
`optee_client`: `$ rg TEEC_ERROR_ITEM_NOT_FOUND | wc -l` --> 12
`optee_test`: `$ rg TEEC_ERROR_ITEM_NOT_FOUND | wc -l` --> 9

Having that said, it can very well come from the TEE itself, hence you'd have to look for `TEE_ERROR_ITEM_NOT_FOUND` (not the 'C' is missing on the first word). So, with that knowledge, what does 1006 do?

1. Calls `TA_OS_TEST_CMD_BASIC` ([here](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_1000.c#L560))
2. I.e, on the TA side we end up in `ta_entry_basic(...)` ([here](https://github.com/OP-TEE/optee_test/blob/master/ta/os_test/os_test.c#L683-L714)).
3. Individual test
 3.1 test_malloc test doesn't return the code
 3.2 test_properties calls a print function that returns the code
 3.3 test_mem_access_right doesn't return the code
 3.4 test_time doesn't return the code
 3.5 test_float doesn't return the code
 3.6 test_setjmp doesn't return the code

I.e., `test_properties` could be worth having an extra look at. If the error code isn't originating from there, then you can at least nail down where it fails in the test TA by adding prints in this function and in the functions it is calling. After knowing roughly where it is failing, then you can attach a debugger ([preferably GDB with QEMU](https://optee.readthedocs.io/building/devices/qemu.html#gdb-secure-world), but you probably have other debug tools for you platform also, JTAG?) and then follow the calls down in the TEE from the TA  at the location just before you're getting the error code. If you step the code in the TEE line by line, it will probably be quite easy to find where it is failing. I know that running GDB in the TEE might seem hard if you've never used GDB before, but TEE development can be pretty challenging, so better take the time to learn the debug tools. It's definitely worth it and will probably save lots of time. Personally I almost never put a debug print when looking for an error, I almost always use GDB, so that makes it possible to print everything, see the callstack, examine memory etc.

But, much of this can probably be avoided if you enable debug prints (and paste the whole log for 1006 here).

**Comment by ashwinnirantar** [comment]
Thank you for the response, I am getting a clearer picture of everything now. 

> please also enable debug prints (`CFG_TEE_CORE_LOG_LEVEL=3 and CFG_TEE_TA_LOG_LEVEL=3`).

Do you know the process to do this for the Yocto builds? 

> `test_properties` could be worth having an extra look at. If the error code isn't originating from there, then you can at least nail down where it fails in the test TA by adding prints in this function and in the functions it is calling

Absolutely, thank you very much! I will do that.

**Comment by ashwinnirantar** [comment]
Also one more thing, I understood your point about drilling down and identifying which function is actually returning the error code - But as can be seen from the error log, the `xtest_teec_open_session` function receives this error code. According to my understanding, the invoke command is separate from the open session command right? So I need to follow the open session function to see which function in turn is returning the error code. 

Thoughts?

**Comment by jbech-linaro** [comment]
> > please also enable debug prints (`CFG_TEE_CORE_LOG_LEVEL=3 and CFG_TEE_TA_LOG_LEVEL=3`).
> 
> Do you know the process to do this for the Yocto builds?

Sorry, I don't. Never used Yocto.

> But as can be seen from the error log, the `xtest_teec_open_session` function receives this error code.

Ok, then it's not related to what I said before. There is not really much happening related to the TA before the session has been opened, so my best guess is that you have not the TA in the correct location or not the correct TA or a TA not correctly built.  I'm afraid I cannot help you anymore, since you're on an unknown device, no logs and a build that we doesn't use/support.

**Comment by vchong** [comment]
> Do you know the process to do this for the Yocto builds?

Change [this](http://git.linaro.org/openembedded/meta-linaro.git/tree/meta-optee/recipes-security/optee/optee-os_git.bb#n37) line to: `oe_runmake all CFG_TEE_CORE_LOG_LEVEL=3 and CFG_TEE_TA_LOG_LEVEL=3`

**Comment by ashwinnirantar** [comment]
> > Do you know the process to do this for the Yocto builds?
> 
> Change [this](http://git.linaro.org/openembedded/meta-linaro.git/tree/meta-optee/recipes-security/optee/optee-os_git.bb#n37) line to: `oe_runmake all CFG_TEE_CORE_LOG_LEVEL=3 and CFG_TEE_TA_LOG_LEVEL=3`

Hi, 

Thank you for the lead, but when I tried this, the build failed with some errors. With just "CFG_TEE_TA_LOG_LEVEL=3" I got no errors in the build, but I didn't get any detailed logs when I tried to run xtest.

**Comment by ashwinnirantar** [comment]
> > > please also enable debug prints (`CFG_TEE_CORE_LOG_LEVEL=3 and CFG_TEE_TA_LOG_LEVEL=3`).
> > 
> > 
> > Do you know the process to do this for the Yocto builds?
> 
> Sorry, I don't. Never used Yocto.
> 
> > But as can be seen from the error log, the `xtest_teec_open_session` function receives this error code.
> 
> Ok, then it's not related to what I said before. There is not really much happening related to the TA before the session has been opened, so my best guess is that you have not the TA in the correct location or not the correct TA or a TA not correctly built. I'm afraid I cannot help you anymore, since you're on an unknown device, no logs and a build that we doesn't use/support.

Yes. So I have narrowed the issue down to the following: 

1) I tried this experiment on the xtests that were passing - 

I changed a couple of bytes in the TA binary and ran the xtests and got the same error as the one I was talking about earlier.

When I changed the binary back to normal it worked perfectly.

2) When I tried to rename the binary to a different name, I would get a TA not found error. 

3) In my case, for the xtests that are failing - I am not getting a "TA not found" error, so the tee-supplicant is able to find the right binary, but perhaps the binary is not the correct one, or is not built correctly as you said.

4) I was reading the OP-TEE documentation and found that the TA binary has a hash appended to the binary and if the hash is different then an error is generated (the normal operation). Now is there any way to get the original TA binary from any source so that I can compare it with the TA I have on my platform, specifically the os_test Trusted application. If I can get the binary from another online source, or from you if you have it, I could test and check. Or if there is any other way to build the TA binary again, that would help as well.

Let me know what you think. 

Thanks a lot for your help.

**Comment by ashwinnirantar** [comment]
Here are the storage space details on my board: 

`df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       144M  107M   26M  81% /
devtmpfs        494M  4.0K  494M   1% /dev
tmpfs           495M  168K  494M   1% /run
tmpfs           495M  192K  494M   1% /var/volatile`

**Comment by ashwinnirantar** [comment]
Hi @jbech-linaro, can you take a look at this please?

**Comment by ashwinnirantar** [comment]
The issue is solved. I made some configuration changes for the heap and stack sizes. It is working now. 

Thanks for your help.

**Comment by tharanirajann** [comment]
@nirantarashwin  I am also getting several errors when I run xtest on ls1xxx platform. Can you please explain how did you resolve the issue by changing heap and stack size. Thanks.
