### ISSUE TITLE
xtest 4110 failure

### ISSUE THREAD

**Issue by dandavid3000** [OP-TEE/optee_test#376]
https://github.com/OP-TEE/optee_test/blob/7c68d7b098b19363ada3c48b133484b018254fb1/host/xtest/regression_4100.c#L440

Hello,

The test will fail because **test_4110_data[6].addres** has strlen equal to 256 so os_len = 257.
In this case, the test asks to convert 257 byte buffer to a 2048 BigInt variable. According to the specification, **TEE_BigIntConvertFromOctetString** returns **TEE_ERROR_OVERFLOW** while the test is expecting a **TEE_SUCESS** at line **1829**.

Could you please check ?
Many thanks,
Dan

**Comment by dandavid3000** [comment]
Hi @jforissier,

The patch works perfectly. Thanks.

**Comment by jforissier** [comment]
@dandavid3000 https://github.com/OP-TEE/optee_test/pull/377, feel free to give a `Reported-by:` and/or a `Tested-by:` tag. Thanks!

**Comment by c-auger** [comment]
It is a little late now that the issue is closed, but if the failure was not reported by OPTEE, maybe that some overflow check is not correctly performed. It might be a security issue in OPTEE and worth to have a look on it, I guess.

**Comment by jforissier** [comment]
@c-auger never too late, but the fact that OP-TEE did not report an error does not necessarily indicate an issue, because the bignum buffers are typically overallocated since their size is computed in multiples of 32-bit words with some space added for overhead. So it could be that the 257th byte would just fit.
That being said, I agree we'd better make sure.

**Comment by c-auger** [comment]
Indeed, it seems that GP does not specify much on how these two 32bits words are to be used, although we could expect them to store the size and the sign somehow. Using one full word for each of them indeed seems to be a waste of space (well, in fact it is not as you are expected to call TEE_BigIntSizeInU32() for allocation, so that you will still waste them anyway).

If you use a single word to store size and sign, then indeed you might have used that extra word. I do not have time to check what exactly is done in OP-TEE for that, though.
