### ISSUE TITLE
xtest 1013 fails with Decompression error when using EARLY_TA_PATHS

### ISSUE THREAD

**Issue by yyyledu** [OP-TEE/optee_test#379]
Running the xtest regression test suite using EARLY_TA_PATHS for all tests fails at test 1013.  Specifically using EARLY_TA_PATHS for the concurrency TA fails with a decompression error. The same error can be caused by increasing MAX_SESSIONS for regression test 1005 (which also uses the Concurrency TA). I am using Optee tagged version 3.7.0.

D/TC:? 0 system_open_ta_binary:239 Lookup user TA ELF e13010e0-2ae1-11e5-896a-0002a5d5c51b (early TA)
D/TC:? 0 system_open_ta_binary:242 res=0x0
E/TC:? 0 read_compressed:206 Decompression error (-4)
D/TC:? 0 tee_ta_invoke_command:772 Error: ffff0000 of 4

To reproduce:
make EARLY_TA_PATHS="../out-br/build/optee_test-1.0/ta/concurrent/out/e13010e0-2ae1-11e5-896a-0002a5d5c51b.stripped.elf" optee-os

Workaround: specify CFG_CORE_HEAP_SIZE=131072

This same symptom is discussed in optee_os issue https://github.com/OP-TEE/optee_os/issues/3285. The error code -4 (Zlib error -4 is Z_MEM_ERROR) gives a clue but is there any way to improve the user experience here, maybe with a better message, or to reduce the heap usage? Should the xtests be expected to pass out-of-the-box using EARLY_TA_PATHS?

**Comment by jforissier** [comment]
> he error code -4 (Zlib error -4 is Z_MEM_ERROR) gives a clue but is there any way to improve the user experience here, maybe with a better message,

Maybe, although I am not convinced it would help a lot. How long did it take for you to figure out -4 was Z_MEM_ERROR and that you were short on heap memory? I guess not much time. Anyway, feel free to submit a patch.

> or to reduce the heap usage? 

I'm all for it if you can find a way.

> Should the xtests be expected to pass out-of-the-box using EARLY_TA_PATHS?

Not really, because adding all the TAs used by xtest as early TAs would take a lot of space (or even adding just the biggest of them I suppose) and the amount of heap space depends on the platform so the more we require, the more likely it will be problematic for some platforms.
Besides, we don't test EARLY_TA_PATHS in CI (that would be good to do at least for a small TA though).

**Comment by jenswi-linaro** [comment]
We could serialize loading early TAs so only one decompression occurs at a time. Or maybe is this such an exotic case that it doesn't matter.

**Comment by yyyledu** [comment]
Not all systems necessarily support a file system and so running xtest with EARLY_TA_PATHS seems like it should be a valid configuration.

As to serializing the TA decompression, the other option of gauging how much heap remains before starting another decompression is probably more work. Are the early TAs the only ones that can hit this concurrency limit?
