### ISSUE TITLE
Fails to build with clang

### ISSUE THREAD

**Issue by rossburton** [OP-TEE/optee_test#452]
Clang doesn't support `-Wmissing-noreturn` or `-Wno-unsafe-loop-optimizations` but these are both passed unconditionally in `host/xtest/Makefile`.

**Comment by jforissier** [comment]
Hi @rossburton,

I think `-Wmissing-noreturn` can be safely removed, we don't really care about this warning I think.

As for `-Wno-unsafe-loop-optimizations`, it was added by 5a83a50 specifically for GCC 7.x. I'd say we can remove it too because [build.git](https://github.com/OP-TEE/build) uses GCC 9.2 and modern Linux distros have more recent versions too.

Would you mind creating a PR?

**Comment by rossburton** [comment]
On it.
