### ISSUE TITLE
Fails to link with musl

### ISSUE THREAD

**Issue by rossburton** [OP-TEE/optee_test#458]
optee-test 3.11.0 when built with the musl C library instead of glibc:
```
aarch64-poky-linux-musl-ld.bfd -e__ta_entry -pie -T [...]/build/ta/os_test/ta.lds -Map=[...]/build/ta/os_test/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.map --sort-section=alignment -z max-page-size=4096  --as-needed   --dynamic-list [...]/build/ta/os_test/dyn_list --eh-frame-hdr  [...]/build/ta/os_test/init.o [...]/build/ta/os_test/os_test.o [...]/build/ta/os_test/ta_entry.o [...]/build/ta/os_test/test_float_subj.o [...]/build/ta/os_test/cxx_tests.o [...]/build/ta/os_test/cxx_tests_c.o [...]/build/ta/os_test/user_ta_header.o -L[...]/build/ta/os_test_lib -los_test -ldl -L[...]/recipe-sysroot/usr/include/optee/export-user_ta/lib --start-group -lutils -lutee -lmbedtls -ldl [...]/recipe-sysroot/usr/lib/libstdc++.a [...]/recipe-sysroot/usr/lib/aarch64-poky-linux-musl/10.2.0/libgcc_eh.a --end-group [...]/recipe-sysroot/usr/lib/aarch64-poky-linux-musl/10.2.0/libgcc.a -lutils -o [...]/build/ta/os_test/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf

aarch64-poky-linux-musl-ld.bfd: [...]/libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::free(void*) [clone .constprop.0]':
[...]/libstdc++-v3/include/aarch64-poky-linux-musl/bits/gthr-default.h:749: undefined reference to `pthread_mutex_lock'
[...]/libstdc++-v3/include/aarch64-poky-linux-musl/bits/gthr-default.h:779: undefined reference to `pthread_mutex_unlock'
```

(repeated in various places)

**Comment by jenswi-linaro** [comment]
I looks like the musl C library doesn't support pthreads. Anything special needed to enable that with musl?

**Comment by rossburton** [comment]
musl does support pthreads, it just integrates the functions directly into libc instead of having a separate library.

**Comment by jenswi-linaro** [comment]
Why the undefined references then?

**Comment by rossburton** [comment]
No idea, it just works for 99.9% of software.  I'm very aware that optee's ta compilation rules are "special".

**Comment by jenswi-linaro** [comment]
I'm confused. Are you linking xtest or some TA?

**Comment by rossburton** [comment]
Just running `make` in optee-test. The failing binary is `ta/os_test`.

**Comment by vchong** [comment]
I've the same issue on AOSP when building with clang, which uses bionic which also integrates pthread functions directly instead of having a separate library. Had to remove the `__thread` qualifier in `ta/os_test` and `ta/os_test_lib` sources to get it to build, but don't remember if that causes failures in the corresponding test in xtest or not. Not sure if it's the right thing to do anyway. [1] provides more background info.

[1] https://github.com/OP-TEE/optee_test/commit/30efcbeaf8864d0f2a5c4be593a5411001fab31b

**Comment by jenswi-linaro** [comment]
It seems that the libstdc++.a compiled with a musl C library depends on being linked with that library too.
I suppose we could try stubbing the missing functions, but that doesn't seem very robust. Stubbing `pthread_mutex_lock()` and `pthread_mutex_unlock()` shouldn't be a problem since TAs are single threaded (so far). I'm more concerned that this is the tip of an iceberg.

It's perhaps best to avoid C++ in TAs altogether when we're left with a libstdc++.a compiled with a musl C library. @jforissier, what do you think?

**Comment by jforissier** [comment]
> It's perhaps best to avoid C++ in TAs altogether when we're left with a libstdc++.a compiled with a musl C library. @jforissier, what do you think?

Agreed. How do we do that though? I think the most convenient way would be to add one or more global flags to enable/disable the problematic test(s), because trying to detect unsupported toolchains etc. in the C code or in the build scripts is not easy and is bound to change. So that would be something like 30efcbeaf886 but simpler with `#if WITH_CPP_TESTS` or something like that (note the commit was later reverted by 513f44514657).

**Comment by jenswi-linaro** [comment]
Something like `#if WITH_CPP_TESTS ` sounds good. Default off in optee_test.git, but enabled when we're building with our build.git. We should preferably have one CI build covering C++ disabled. This should take care of the short term problem.

For the longer term we may need to stop using the `libstdc++.a` shipped with the compiler since it's not unreasonable for `libstdc++.a` to have dependencies to the libc shipped with the compiler. Perhaps it's possible to recompile `libstdc++.a` with libutils. This will probably require a bit work though.

**Comment by rossburton** [comment]
@jforissier did that series of patches resolve this issue entirely?

**Comment by jforissier** [comment]
@rossburton you tell me :)

Short answer: yes I think so.
Long answer: the patches make the C++ TA tests "opt-in" rather than "opt-out", and they are enabled only in our own build/test environment https://github.com/OP-TEE/build (typically cloned from https://github.com/OP-TEE/manifest). The idea being, the C++ should remain disabled unless we know the toolchain is compatible etc. So hopefully if you update everything to latest (optee_os and optee_test) you should not see any link error anymore.

**Comment by rossburton** [comment]
Failed to action the stale notification and suddenly over a week goes by.

Can someone reopen this?

**Comment by jenswi-linaro** [comment]
If https://github.com/OP-TEE/optee_test/pull/464 did resolve this perhaps we can close this issue.
