### ISSUE TITLE
error: implicit declaration of function 'RSA_set0_key'

### ISSUE THREAD

**Issue by clementfaure** [OP-TEE/optee_test#592]
Hello @jforissier,

I have a compilation issue with this commit https://github.com/OP-TEE/optee_test/commit/0915b2243399511a7485fa82e2798a9324f2f60b and an OpenSSL function call.
My configuration is the following : `WITH_OPENSSL=y` and `OPTEE_OPENSSL_EXPORT` is unset.

```
| tmp/work/armv8a-poky-linux/optee-test/upstream.imx-r0/git/host/xtest/regression_1000.c: In function 'set_att_key':
| tmp/work/armv8a-poky-linux/optee-test/upstream.imx-r0/git/host/xtest/regression_1000.c:2760:14: error: implicit declaration of function 'RSA_set0_key'; did you mean 'RSA_check_key'? [-Werror=implicit-function-declaration]
|  2760 |         st = RSA_set0_key(att_key, bn_n, bn_e, BN_new());
|       |              ^~~~~~~~~~~~
|       |              RSA_check_key
|
```

It looks like `RSA_set0_key()` is not available in the OpenSSL version embedded with optee-test ... Is it done on purpose ? Should we add a check on `OPENSSL_VERSION_NUMBER` before calling this function?

**Comment by jforissier** [comment]
Hi @clementfaure,


> It looks like `RSA_set0_key()` is not available in the OpenSSL version embedded with optee-test ...

Bummer...

> Is it done on purpose ?

Absolutely not - sorry for breaking you build :-/
I didn't notice when I wrote this code because I tested in the standard OP-TEE development [environment](https://github.com/OP-TEE/manifest/blob/master/qemu_v8.xml) which uses Buildroot, so the the OpenSSL lib included with the source is not used. 

> Should we add a check on `OPENSSL_VERSION_NUMBER` before calling this function?

Sounds like a good idea. Would you mind proposing a fix? If at all possible I'd like to get rid of the precompiled libraries in the optee_test tree, but perhaps some people still depend on it.

**Comment by jforissier** [comment]
> > If at all possible I'd like to get rid of the precompiled libraries in the optee_test tree, but perhaps some people still depend on it.
> 
> That is my question, actually : why would we include a specific version of OpenSSL in optee-test if there are no requirements for tests to use this specific embedded library? Based on your answer, I guess we can remove it now, optee-test does not compile properly anymore ...

Sure, but with a fix based on SSL version we can still have the current embedded OpenSSL be used for all cases except this one.

> > Sounds like a good idea. Would you mind proposing a fix?
> 
> I will do it. So you guys use OpenSSL 1.1.1 right?

Yes 1.1.1l (lowercase L). Thanks!

**Comment by clementfaure** [comment]
> Sure, but with a fix based on SSL version we can still have the current embedded OpenSSL be used for all cases except this one.

I see, so what are the requirements for the embedded OpenSSL version in optee-test to be upgraded?

**Comment by jforissier** [comment]
I think we could simply build new libcrypto.a files, version 1.1.1l, to replace the existing ones. Thus synchronizing with the Buildroot environment which works fine (and which is used by many developers and CI etc.)

**Comment by clementfaure** [comment]
That solution would be coherent IMO

**Comment by jforissier** [comment]
> That solution would be coherent IMO

Yes but note it would also mean updating the header files (`host/openssl/include`). Since I personally have no way of testing with the embedded OpenSSL (as I said I'm using the Buildroot environment which uses `host/xtest/CMakeLists.txt`), it seems more reasonable to just add a test on `OPENSSL_VERSION_NUMBER`. The embedded libraries and header should be considered deprecated and at some point we should remove them (the Makefile already supports specifying a path via `OPTEE_OPENSSL_EXPORT`).
