### ISSUE TITLE
ECDSA verify test

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_test#642]
Please could I get some background about this hardcoded value in test 4006?

https://github.com/OP-TEE/optee_test/blob/3.20.0/host/xtest/regression_4000.c#L3707

Adding a code snipped in case the file I am pointing to changes

```
  	if (tv->mode == TEE_MODE_VERIFY || tv->mode == TEE_MODE_SIGN) {
			if (TEE_ALG_GET_MAIN_ALG(tv->algo) == TEE_MAIN_ALGO_ECDSA)
				hash_algo = TEE_ALG_SHA1;
#if defined(CFG_CRYPTO_RSASSA_NA1)
			else if (tv->algo == TEE_ALG_RSASSA_PKCS1_V1_5)
				hash_algo = TEE_ALG_SHA256;
#endif

```
Why is this hardcoded to SHA1 for ECDSA?

**Comment by etienne-lms** [comment]
The test vectors used include a pre-computed signature of the plain text data, used to test verification. The test vectors are based on NIST FIPS 186-2 one can found at [csrc.nist.gov/Cryptographic-Algorithm-Validation-Program](https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Digital-Signatures#ecdsa2vs) (section Test Vectors). It seems these signatures were all computed based on a SHA1 hash of the plain text data, even if it is not stated anywhere.

FIPS 186-4 Test Vectors referenced at the same URL provide precomputed signatures based on several applicable SHAx hash of plain text vector, rather than only SHA1. We could update our tests to cover some of thoses.

**Comment by nathan-menhorn** [comment]
Hi @etienne-lms as NIST officially recommends retiring SHA1 due to collision and other issues, https://www.nist.gov/image/sha-1-retirement, is it possible to move away from SHA1 and upgrade OP-TEE to use SHA2 and SHA3 instead?

**Comment by etienne-lms** [comment]
The test checks the signature process, not really protecting the content of the payload, so using another hash won't make the test more robust. That said, it makes sense to preferrably not use SHA1 on the tests when possible. Do you want to propose an P-R?

**Comment by nathan-menhorn** [comment]
Leaving issue open. Currently, no time to work on this this and sounds like @ldts is getting ready for Embedded World and working on other priorities as well.

**Comment by ldts** [comment]
sorry yes, have been spending sometime supporting our product with TPMs - needed ECDH1-derive added to the tpm2_pkcs11 stack https://github.com/tpm2-software/tpm2-pkcs11/commit/cd7b486414a2e8819e94a6ef60c0243726c9f68f 

I also have a fix for openssl  3.x so that TPM2 supports the legacy engine interface (some changes missing in the key translation code at crypto/evp/ctrl_params_translate.c

I might be able to look into this after EW23

**Comment by nathan-menhorn** [comment]
Pinging to leave open.
