### ISSUE TITLE
-Werror being used with code not being -Werror safe.

### ISSUE THREAD

**Issue by koenkooi** [OP-TEE/optee_test#87]
The general preference in the open source world is to only enable -Werror in maintainer mode (e.g. 'make dist') since it's hard to predict how sensitive $compiler will be in the future. Case in point:

host/xtest/xtest_benchmark_1000.c:94:20: warning: 'spent_time' may be used uninitialized in this function [-Wmaybe-uninitialized]

While this looks to be a false positive, it breaks the build since -Werror is hardcoded in the Makefile.

**Comment by pascal-brand-st-dev** [comment]
Right.
Feel free to propose a contribution, as described in https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#contributing-1

Thanks,
Pascal.

**Comment by kuscsik** [comment]
https://github.com/OP-TEE/optee_test/pull/95

**Comment by fboudra** [comment]
@pascal-brand-st @jbech-linaro the bug has been reported 18 days ago, it's a one-liner and all we get is a reviewed-by ???

**Comment by jbech-linaro** [comment]
@fboudra, it was reported 18 days ago and Pascal asked for a pull request 18 days ago. Whether it's a one-liner is irrelevant. It's just as easy for developer A to send a pull request as developer B. We haven't seen any pull request until 4 hours ago, which Pascal reviewed immediately. After the review tag, the tag shall be applied and after that it will be merged. Also everything that is officially supported is working and has been working since this was reported, so please calm down!

And regarding `-Werror` we have deliberately added that to catch errors. Even though this is just test code in this particular git, we're dealing with security related code and therefore **want** to convert warnings to errors.

**Comment by fboudra** [comment]
@jbech-linaro what's the point of reviewed-by? it's a trivial one-liner patch that could have been done 18 days ago. Some patches are 24 days old with several reviewed-by and are still not merged. This patch shouldn't be pending, it should be merged already. What's your process to get the patches merged?

**Comment by koenkooi** [comment]
For the record, I'm not a programmer, I do not know C++. So asking me to do a pull request is hilarious. 

The 18 days wait also shows you don't really care about -Werror issues, otherwise you would have looked at it yourself and fixed it. Blaming me for not providing a pull request is both lazy and condescending.

**Comment by kuscsik** [comment]
I pushed an updated patch with the review tag.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question/report has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
