### ISSUE TITLE
TEEC_AllocateSharedMemory with TEEC_MEMREF_PARTIAL_OUTPUT/INPUT

### ISSUE THREAD

**Issue by flowher** [OP-TEE/optee_test#90]
Hi,

I've found here (GP tests):
https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xml/include/xml_crypto_api.h#L808

that sometimes you use TEEC_MEMREF_PARTIAL_OUTPUT (INPUT) flag when calling TEEC_AllocateSharedMemory. Shouldn't it be a TEEC_MEM_OUTPUT(INPUT) flag instead?

I think TEEC_MEMREF_PARTIAL shouldn't  be used for TEEC_AllocateShareMemory, isn't? As far as I understand it is useful when constructing param types with TEEC_PARAM_TYPES(). Or am I completely wrong?

**Comment by jforissier** [comment]
I think you're right. The GP Client API spec v1.0 states that "All other bits in this field SHOULD be set to zero, and are reserved for future use".
I tried replacing TEEC_MEMREF_PARTIAL_OUTPUT with TEEC_MEM_OUTPUT (and similarly for INPUT) in xml_crypto_api.h, and the tests still run fine. So I guess we should fix the tests. And, possibly also optee_client because I would not expect the tests to pass when the required flags are missing.
@pascal-brand-st-dev what's your opinion?

**Comment by pascal-brand-st-dev** [comment]
You look right.
Do not hesitate to suggest a pull-request to fix optee_test, and also to add checks in optee_client.

**Comment by flowher** [comment]
Ok, I'm on it.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the patch for it has been merged. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
